### PR TITLE
add linklyhq

### PR DESCRIPTION
**Pull request by ignoramous**
https://archive.is/HOH1N

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@ignoramous maybe `l.linklyhq.com` is more suitable?

**Comment by ignoramous** [comment]
In the examples on their website, I also see `linklyhq.com/l/*`...

**Comment by ignoramous** [comment]
Btw, `l.linklyhq.com` already exists in this list.

**Comment by PeterDaveHello** [comment]
@ignoramous I tried to find out some existing links, didn't see linklyhq.com/l/* in real cases, do you have some as reference?

**Comment by ignoramous** [comment]
> do you have some as reference?

No, I don't use linkyhq nor have have I stumbled upon `linkyhq.com/l` links; I am only going by the screenshots on the linkyhq homepage ([ref](https://archive.is/Xzel7)).

**Comment by PeterDaveHello** [comment]
@ignoramous thanks for the info, as I can't find any real cases yet, maybe it's just really an "example"? Would like to suggest that we can add it when it's confirmed to be using ;)

**Comment by ignoramous** [comment]
Sure, makes sense. I'll close it for now, then.

**Comment by PeterDaveHello** [comment]
@ignoramous Still thanks for your contribution! Please also feel free to add some others 🤩

**Comment by ignoramous** [comment]
Unresolved conflicts... closing.

**Pull request closed without merging**
