### PR TITLE
add prbly.us

### PR DESCRIPTION
**Pull request by ignoramous**
ref: https://archive.is/zXkqi

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@ignoramous Thank you for your contribution. To expedite the review process, please include both the source and target URLs in the PR description. We'd greatly appreciate it.

**Comment by ignoramous** [comment]
The archive.is link shows both source and target?

**Comment by PeterDaveHello** [comment]
@ignoramous yeah but the content is outside GitHub, it's more like I have another short link in the PR.

**Comment by ignoramous** [comment]
> yeah but the content is outside GitHub, it's more like I have another short link in the PR.

Gotcha. I use `archive.is` to show the link was active and redirecting to a valid webpage. It creates a permanent record.

**Pull request merged**
