### PR TITLE
Update list

### PR DESCRIPTION
**Pull request by drego85**
Updated list from Phishing Army source.

### CODE REVIEW

**Review by PeterDaveHello — CHANGES_REQUESTED** [review]
I appreciate the pull request, unfortunately, the CI failed, there are so many duplicated domains, and there's also no evidence of they're being alive. It'll be very hard to merge such a large patch. May I respectfully suggest to separate and verify each of them, and send them in individual pull requests? Thanks.

**Comment by drego85** [comment]
Hi Guys,
sorry but it is a period where I'm very busy.

I hope to do a new, more accurate PR in the coming weeks.

I'm closing this PR.

**Comment by PeterDaveHello** [comment]
@spirillen thanks, but that's not the reason why I didn't do it.

We got high quality data in this project, all of them are verified before added, and keep monitoring and removing invalid ones.

Adding a large amount of them without proper verification is not I want, though I really appreciate of contributions, still, we need to make sure what's really going on before get it done.

**Comment by spirillen** [comment]
Me neither, everything is tested and verified at mypdns too, but I ended up only to test  140 of them with the commit bot, then we will se how few I need to test manually :) If they get to low score with the commit bot (kind of grey listing).

```
Status      Percentage   Amount
----------- ------------ ------------
ACTIVE      26%          140
INACTIVE    74%          404
INVALID     1%           4
```

**Comment by spirillen** [comment]
> We got high quality data in this project

So you mean My Privacy DNS do not have accurate data?

**Comment by PeterDaveHello** [comment]
> > We got high quality data in this project
> 
> So you mean My Privacy DNS do not have accurate data?

That's not what I mean, but the verification can't be automatic here, it's not just availability check of domain name and http/s services, but the actual URL shorten services alive.

**Comment by spirillen** [comment]
These did not make it by the report bot

```css
126.am
ezurl.cc
adjix.com
catchylink.com
sharetabs.com
8u.cz
cutt.eu
web99.eu
azali.fr
qrtag.fr
w1p.fr
7li.in
b54.in
tinyvid.io
hurl.it
trunc.it
cut.ly
brzu.net
ble.pl
fff.re
hec.su
blip.tv
```

These how ever made it through to the commit bot

- `4i.ae`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645838
- `kl.am`: https://0xacab.org/my-privacy-dns/matrix/-/issues/16233
- `dft.ba`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645790
- `oua.be`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645800
- `ur1.ca`: https://0xacab.org/my-privacy-dns/matrix/-/issues/18526
- `4url.cc`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645777
- `7fth.cc`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645776
- `ex9.co`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645791
- `hadej.co`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645802
- `1url.com`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645774
- `2ya.com`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2279
- `m3mi.com`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645804
- `u.mavrev.com`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645826
- `qicute.com`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2745
- `sharein.com`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2883
- `shrinkee.com`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645808
- `shrinkster.com`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2788
- `snipr.com`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2944
- `snipurl.com`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2945
- `snurl.com`: https://0xacab.org/my-privacy-dns/matrix/-/issues/3106
- `starturl.com`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2851
- `tldrify.com`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645815
- `traceurl.com`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645817
- `twitterpan.com`: https://0xacab.org/my-privacy-dns/matrix/-/issues/17830
- `twitthis.com`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2914
- `urlcover.com`: https://0xacab.org/my-privacy-dns/matrix/-/issues/3102
- `urlkr.com`: https://0xacab.org/my-privacy-dns/matrix/-/issues/3010
- `urlot.com`: https://0xacab.org/my-privacy-dns/matrix/-/issues/18412
- `urlpire.com`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2921
- `virl.com`: https://0xacab.org/my-privacy-dns/matrix/-/issues/3038
- `xr.com`: https://0xacab.org/my-privacy-dns/matrix/-/issues/3051
- `yect.com`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645836
- `zoodl.com`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645840
- `kratsi.cz`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645796
- `qxp.cz`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645810
- `2u.xf.cz`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645843
- `xoe.cz`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645827
- `tohle.de`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645820
- `u6e.de`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2993
- `url4.eu`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2998
- `wb1.eu`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645834
- `ping.fm`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2754
- `b00.fr`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645788
- `cybr.fr`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645789
- `iky.fr`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645807
- `pic.gd`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2790
- `a.gg`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2266
- `any.gs`: https://0xacab.org/my-privacy-dns/matrix/-/issues/139746
- `unyku.id`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645825
- `urlx.ie`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2994
- `ccj.im`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645794
- `tr.im`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2919
- `1link.in`: https://0xacab.org/my-privacy-dns/matrix/-/issues/3749
- `2ty.in`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645775
- `alil.in`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645778
- `asso.in`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645781
- `bitw.in`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645782
- `captur.in`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645783
- `c-o.in`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2412
- `shrt.in`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645824
- `tr5.in`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645822
- `past.is`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645798
- `htxt.it`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2567
- `rickroll.it`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645805
- `sqrl.it`: https://0xacab.org/my-privacy-dns/matrix/-/issues/18402
- `yep.it`: https://0xacab.org/my-privacy-dns/matrix/-/issues/18250
- `xurl.jp`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645842
- `adv.li`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645779
- `tin.li`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645811
- `wed.li`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645832
- `bul.lu`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645786
- `fur.ly`: https://0xacab.org/my-privacy-dns/matrix/-/issues/70125
- `good.ly`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645792
- `om.ly`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2730
- `trick.ly`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645816
- `4view.me`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645841
- `bloat.me`: https://0xacab.org/my-privacy-dns/matrix/-/issues/10280
- `bote.me`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645785
- `buk.me`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2408
- `folu.me`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645797
- `hops.me`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645806
- `shortna.me`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2910
- `trck.me`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645819
- `vgn.me`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645831
- `wwy.me`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645839
- `xub.me`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645833
- `ri.ms`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2759
- `tiny.ms`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645814
- `5url.net`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645844
- `23o.net`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645773
- `idek.net`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2570
- `zxq.net`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645837
- `korta.nu`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2615
- `kd2.org`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645795
- `urlx.org`: https://0xacab.org/my-privacy-dns/matrix/-/issues/3031
- `sy.pe`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645818
- `short.pk`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645809
- `ln-s.ru`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645799
- `qbn.ru`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645813
- `abbr.sk`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645780
- `po.st`: https://0xacab.org/my-privacy-dns/matrix/-/issues/19545
- `brk.to`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645787
- `cyonix.to`: https://0xacab.org/my-privacy-dns/matrix/-/issues/37606
- `gat.to`: https://0xacab.org/my-privacy-dns/matrix/-/issues/372545
- `parky.tv`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645803
- `shortlinks.co.uk`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2814
- `2tu.us`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2285
- `snsw.us`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645821
- `turo.us`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2870
- `unlc.us`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645830
- `vt802.us`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645829
- `fly2.ws`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2517
- `hurl.ws`: https://0xacab.org/my-privacy-dns/matrix/-/issues/2575
- `trkr.ws`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645823
- `xn--ki8h.ws`: https://0xacab.org/my-privacy-dns/matrix/-/issues/645835

**Comment by spirillen** [comment]
Your welcome... also to merge your project into or by using our tool park. For those records you then would like to whitelist... well you just make a `grep -v` between your own whitelist and the list on mypdns.

You find the public toolkit at https://0xacab.org/my-privacy-dns/matrix/-/tree/master/tools If you believe you can't find what you need, just ask

This way most people and users win. I never understood why we need to run and maintain all these blacklists, which is why the domain index with the reasons for why something is blocked or not, actually is my primary project... not the blacklist, they are the product of the verdict.

And you can't find as much as 1 subdomain on any of the lists without and issue. (Known fact we lost a server with ~9mill issues I do have the backup of those issues in case it should be required)

**Pull request closed without merging**
